version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/twitter-sentiment

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - run:
          name: install dependencies
          command: |
            python3 -m venv twitter_sentiment
            . twitter_sentiment/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./twitter_sentiment
            - /usr/local/bin
            - /usr/local/lib/python3.6/site-packages
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  runLibraryTest:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run twitter_sentiment tests
          command: |
            . twitter_sentiment/bin/activate
            cd test/
            python3 -m unittest test_twitterSentiment

      - save_cache:
          paths:
            - ./twitter_sentiment
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: verify git tag vs version
          command: |
            . twitter_sentiment/bin/activate
            python3 setup.py verify

      - run:
          name: create package files
          command: |
            python3 setup.py sdist bdist_wheel

      - run:
          name: create .pypirc file
          command: |
            echo -e "[pypi]" >> .pypirc
            echo -e "repository = https://pypi.org/legacy/"
            echo -e "username = TeddyCr" >> .pypirc
            echo -e " = $PYPI_PASSWORD" >> .pypirc

      - run:
          name: upload package to pypi server
          command: |
            . twitter_sentiment/bin/activate
            twin upload dist/*

      - save_cache:
          paths: 
            - ./twitter_sentiment
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - runLibraryTest:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/

            branches:
              ignore: /.*/

      - deploy:
          requires:
            - runLibraryTest
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/


          



